#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPAnim_FastTravelStation

#include "Basic.hpp"

#include "BPAnim_FastTravelStation_classes.hpp"
#include "BPAnim_FastTravelStation_parameters.hpp"


namespace SDK
{

// Function BPAnim_FastTravelStation.BPAnim_FastTravelStation_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UBPAnim_FastTravelStation_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_FastTravelStation_C", "AnimGraph");

	Params::BPAnim_FastTravelStation_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

