#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_MeteorDestroyer_RailgunInfo

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_MeteorDestroyer_RailgunInfo.BPI_MeteorDestroyer_RailgunInfo_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_MeteorDestroyer_RailgunInfo_C final
{
public:
	void MeteorExplode();
	void RemindManagerFinished();
	void RemindMeteorFinished();
	void SetManager(class AActor* Manager);
	void StartExplode();
	void TransferAcceleration(double Acceleration);
	void TransferExplosionCount(int32 ExplosionCount);
	void TransferLoadedOreCount(int32 LoadedOreCount);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_MeteorDestroyer_RailgunInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_MeteorDestroyer_RailgunInfo_C")
	}
	static class IBPI_MeteorDestroyer_RailgunInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_MeteorDestroyer_RailgunInfo_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_MeteorDestroyer_RailgunInfo_C;

}

