#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DC_Fixt_Candle_Single_D

#include "Basic.hpp"

#include "DC_Fixture_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DC_Fixt_Candle_Single_D.DC_Fixt_Candle_Single_D_C
// 0x0010 (0x0A20 - 0x0A10)
class ADC_Fixt_Candle_Single_D_C final : public ADC_Fixture_C
{
public:
	class UStaticMeshComponent*                   SM_FX_CandleFlame;                                 // 0x0A08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Candle_Small_B;                                 // 0x0A10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x0A18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DC_Fixt_Candle_Single_D_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DC_Fixt_Candle_Single_D_C")
	}
	static class ADC_Fixt_Candle_Single_D_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADC_Fixt_Candle_Single_D_C>();
	}
};
DUMPER7_ASSERTS_ADC_Fixt_Candle_Single_D_C;

}

