#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DC_Fixt_Strip_Tube_100_Double

#include "Basic.hpp"

#include "DC_Fixture_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DC_Fixt_Strip_Tube_100_Double.DC_Fixt_Strip_Tube_100_Double_C
// 0x0020 (0x0A30 - 0x0A10)
class ADC_Fixt_Strip_Tube_100_Double_C final : public ADC_Fixture_C
{
public:
	class UStaticMeshComponent*                   SM_Light_Bulb_Tube_101;                            // 0x0A08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Light_Bulb_Tube_100;                            // 0x0A10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x0A18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_MERGED_Strip_Tube_100_Double;                   // 0x0A20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DC_Fixt_Strip_Tube_100_Double_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DC_Fixt_Strip_Tube_100_Double_C")
	}
	static class ADC_Fixt_Strip_Tube_100_Double_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADC_Fixt_Strip_Tube_100_Double_C>();
	}
};
DUMPER7_ASSERTS_ADC_Fixt_Strip_Tube_100_Double_C;

}

