#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DC_Fixt_Ripper_Exhaust_A

#include "Basic.hpp"

#include "DC_Fixture_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DC_Fixt_Ripper_Exhaust_A.DC_Fixt_Ripper_Exhaust_A_C
// 0x0020 (0x0A30 - 0x0A10)
class ADC_Fixt_Ripper_Exhaust_A_C final : public ADC_Fixture_C
{
public:
	class UPointLightComponent*                   PointLight;                                        // 0x0A08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Light_Bulb_Single_Cylinder1;                    // 0x0A10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Light_Bulb_Single_Cylinder;                     // 0x0A18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Lights_Thick_A_;                                // 0x0A20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DC_Fixt_Ripper_Exhaust_A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DC_Fixt_Ripper_Exhaust_A_C")
	}
	static class ADC_Fixt_Ripper_Exhaust_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADC_Fixt_Ripper_Exhaust_A_C>();
	}
};
DUMPER7_ASSERTS_ADC_Fixt_Ripper_Exhaust_A_C;

}

