#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_Blockout_SizeTemplate

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_Blockout_SizeTemplate.E_Blockout_SizeTemplate
// NumValues: 0x0009
enum class E_Blockout_SizeTemplate : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator5                           = 5,
	NewEnumerator6                           = 6,
	NewEnumerator7                           = 7,
	E_Blockout_MAX                           = 8,
};

}

