#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_ScatterAlongSpline_Spacing

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_ScatterAlongSpline_Spacing.E_ScatterAlongSpline_Spacing
// NumValues: 0x0007
enum class E_ScatterAlongSpline_Spacing : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator4                           = 3,
	NewEnumerator5                           = 4,
	NewEnumerator6                           = 5,
	E_ScatterAlongSpline_MAX                 = 6,
};

}

