#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_PropagandaSpeaker_ZoneTypes

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Enum_PropagandaSpeaker_ZoneTypes.Enum_PropagandaSpeaker_ZoneTypes
// NumValues: 0x0005
enum class Enum_PropagandaSpeaker_ZoneTypes : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	Enum_PropagandaSpeaker_MAX               = 4,
};

}

