#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_SpawnMesh_Door_Small_AnimStyle

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Enum_SpawnMesh_Door_Small_AnimStyle.Enum_SpawnMesh_Door_Small_AnimStyle
// NumValues: 0x0006
enum class Enum_SpawnMesh_Door_Small_AnimStyle : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator5                           = 4,
	Enum_SpawnMesh_Door_Small_MAX            = 5,
};

}

