#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GbxFaceFX

#include "Basic.hpp"

#include "GbxFaceFX_classes.hpp"
#include "GbxFaceFX_parameters.hpp"


namespace SDK
{

// Function GbxFaceFX.FaceFXOwner.PlayFaceFXAnim
// (Native, Public, BlueprintCallable)
// Parameters:
// class UFaceFXAnim*                      FaceFXAnim                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void IFaceFXOwner::PlayFaceFXAnim(class UFaceFXAnim* FaceFXAnim)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("FaceFXOwner", "PlayFaceFXAnim");

	Params::FaceFXOwner_PlayFaceFXAnim Parms{};

	Parms.FaceFXAnim = FaceFXAnim;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	AsUObject()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function GbxFaceFX.FaceFXOwner.PlayFaceFXAnimById
// (Native, Public, BlueprintCallable)
// Parameters:
// class UFaceFXAnimSet*                   FaceFXAnimSet                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             Group                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             AnimName                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLoop                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGbxAudioPlaybackInstance& OptionalAudioInstance                                  (Parm, NativeAccessSpecifierPublic)
// const class UObject*                    Caller                                                 (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool IFaceFXOwner::PlayFaceFXAnimById(class UFaceFXAnimSet* FaceFXAnimSet, class FName Group, class FName AnimName, bool bLoop, const struct FGbxAudioPlaybackInstance& OptionalAudioInstance, const class UObject* Caller)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("FaceFXOwner", "PlayFaceFXAnimById");

	Params::FaceFXOwner_PlayFaceFXAnimById Parms{};

	Parms.FaceFXAnimSet = FaceFXAnimSet;
	Parms.Group = Group;
	Parms.AnimName = AnimName;
	Parms.bLoop = bLoop;
	Parms.OptionalAudioInstance = std::move(OptionalAudioInstance);
	Parms.Caller = Caller;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	AsUObject()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

