#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GbxNiagaraExtensions

#include "Basic.hpp"

#include "GbxNiagaraExtensions_classes.hpp"
#include "GbxNiagaraExtensions_parameters.hpp"


namespace SDK
{

// Function GbxNiagaraExtensions.GbxNiagaraDataInterfaceSampleDynamicMeshBase.OnSourceEndPlay
// (Final, Native, Protected)
// Parameters:
// class AActor*                           InSource                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EEndPlayReason                          reason                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UGbxNiagaraDataInterfaceSampleDynamicMeshBase::OnSourceEndPlay(class AActor* InSource, EEndPlayReason reason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GbxNiagaraDataInterfaceSampleDynamicMeshBase", "OnSourceEndPlay");

	Params::GbxNiagaraDataInterfaceSampleDynamicMeshBase_OnSourceEndPlay Parms{};

	Parms.InSource = InSource;
	Parms.reason = reason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function GbxNiagaraExtensions.GbxNiagaraPerfCollectorBPLibrary.CanStartNiagaraPerfTest
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UGbxNiagaraPerfCollectorBPLibrary::CanStartNiagaraPerfTest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("GbxNiagaraPerfCollectorBPLibrary", "CanStartNiagaraPerfTest");

	Params::GbxNiagaraPerfCollectorBPLibrary_CanStartNiagaraPerfTest Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function GbxNiagaraExtensions.GbxNiagaraPerfCollectorBPLibrary.GetNiagaraPerfTestStatus
// (Final, Native, Static, Private, HasOutParams, BlueprintCallable)
// Parameters:
// int32*                                  TotalTests                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32*                                  RemainingTests                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EGbxNiagaraPerfCollectorState           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EGbxNiagaraPerfCollectorState UGbxNiagaraPerfCollectorBPLibrary::GetNiagaraPerfTestStatus(int32* TotalTests, int32* RemainingTests)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("GbxNiagaraPerfCollectorBPLibrary", "GetNiagaraPerfTestStatus");

	Params::GbxNiagaraPerfCollectorBPLibrary_GetNiagaraPerfTestStatus Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (TotalTests != nullptr)
		*TotalTests = Parms.TotalTests;

	if (RemainingTests != nullptr)
		*RemainingTests = Parms.RemainingTests;

	return Parms.ReturnValue;
}


// Function GbxNiagaraExtensions.GbxNiagaraPerfCollectorBPLibrary.SetNiagaraPerfTestSystemOffset
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// float                                   NewOffset                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UGbxNiagaraPerfCollectorBPLibrary::SetNiagaraPerfTestSystemOffset(float NewOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("GbxNiagaraPerfCollectorBPLibrary", "SetNiagaraPerfTestSystemOffset");

	Params::GbxNiagaraPerfCollectorBPLibrary_SetNiagaraPerfTestSystemOffset Parms{};

	Parms.NewOffset = NewOffset;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function GbxNiagaraExtensions.GbxNiagaraPerfCollectorBPLibrary.StartNiagaraPerfTest
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UGbxNiagaraPerfCollectorBPLibrary::StartNiagaraPerfTest(class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("GbxNiagaraPerfCollectorBPLibrary", "StartNiagaraPerfTest");

	Params::GbxNiagaraPerfCollectorBPLibrary_StartNiagaraPerfTest Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function GbxNiagaraExtensions.GbxNiagaraPerfCollectorBPLibrary.StopNiagaraPerfTest
// (Final, Native, Static, Private, BlueprintCallable)

void UGbxNiagaraPerfCollectorBPLibrary::StopNiagaraPerfTest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("GbxNiagaraPerfCollectorBPLibrary", "StopNiagaraPerfTest");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

