#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GbxPatch

#include "Basic.hpp"

#include "DeveloperSettings_classes.hpp"


namespace SDK
{

// Class GbxPatch.GbxPatchSettings
// 0x0008 (0x0040 - 0x0038)
class UGbxPatchSettings final : public UDeveloperSettings
{
public:
	int32                                         CountDownToRebootSecs;                             // 0x0038(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PendingResponseTimeoutSecs;                        // 0x003C(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GbxPatchSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GbxPatchSettings")
	}
	static class UGbxPatchSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGbxPatchSettings>();
	}
};
DUMPER7_ASSERTS_UGbxPatchSettings;

}

