#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GbxPrefab

#include "Basic.hpp"

#include "GbxPrefab_classes.hpp"
#include "GbxPrefab_parameters.hpp"


namespace SDK
{

// Function GbxPrefab.GbxPrefabComponentModifierInterface.CanModifyComponent
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UActorComponent*                  Component                                              (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool IGbxPrefabComponentModifierInterface::CanModifyComponent(class UActorComponent* Component)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("GbxPrefabComponentModifierInterface", "CanModifyComponent");

	Params::GbxPrefabComponentModifierInterface_CanModifyComponent Parms{};

	Parms.Component = Component;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	AsUObject()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function GbxPrefab.GbxPrefabComponentModifierInterface.GetInstanceParametersStruct
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UScriptStruct*                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UScriptStruct* IGbxPrefabComponentModifierInterface::GetInstanceParametersStruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("GbxPrefabComponentModifierInterface", "GetInstanceParametersStruct");

	Params::GbxPrefabComponentModifierInterface_GetInstanceParametersStruct Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	AsUObject()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function GbxPrefab.GbxPrefabComponentModifierInterface.GetInstanceParamName
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString IGbxPrefabComponentModifierInterface::GetInstanceParamName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("GbxPrefabComponentModifierInterface", "GetInstanceParamName");

	Params::GbxPrefabComponentModifierInterface_GetInstanceParamName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	AsUObject()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function GbxPrefab.GbxPrefabComponentModifierInterface.GetModifierTag
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString IGbxPrefabComponentModifierInterface::GetModifierTag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("GbxPrefabComponentModifierInterface", "GetModifierTag");

	Params::GbxPrefabComponentModifierInterface_GetModifierTag Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	AsUObject()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function GbxPrefab.GbxPrefabComponentModifierInterface.IsInstanceEditable
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool IGbxPrefabComponentModifierInterface::IsInstanceEditable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("GbxPrefabComponentModifierInterface", "IsInstanceEditable");

	Params::GbxPrefabComponentModifierInterface_IsInstanceEditable Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	AsUObject()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function GbxPrefab.GbxPrefabComponentModifierInterface.ModifyComponent
// (Native, Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UActorComponent*                  Component                                              (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FRandomStream&             RandomStream                                           (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void IGbxPrefabComponentModifierInterface::ModifyComponent(class UActorComponent* Component, const struct FRandomStream& RandomStream)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("GbxPrefabComponentModifierInterface", "ModifyComponent");

	Params::GbxPrefabComponentModifierInterface_ModifyComponent Parms{};

	Parms.Component = Component;
	Parms.RandomStream = std::move(RandomStream);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	AsUObject()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

