#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GbxUISettings

#include "Basic.hpp"

#include "InputCore_structs.hpp"


namespace SDK
{

// Enum GbxUISettings.ESubtitlesSettings
// NumValues: 0x0004
enum class ESubtitlesSettings : uint8
{
	Off                                      = 0,
	WithoutCC                                = 1,
	WithCC                                   = 2,
	ESubtitlesSettings_MAX                   = 3,
};

// Enum GbxUISettings.ESubtitlesTextSize
// NumValues: 0x0006
enum class ESubtitlesTextSize : uint8
{
	ExtraSmall                               = 0,
	Small                                    = 1,
	Medium                                   = 2,
	Large                                    = 3,
	ExtraLarge                               = 4,
	ESubtitlesTextSize_MAX                   = 5,
};

// Enum GbxUISettings.ESubtitlesTextColor
// NumValues: 0x0003
enum class ESubtitlesTextColor : uint8
{
	White                                    = 0,
	Yellow                                   = 1,
	ESubtitlesTextColor_MAX                  = 2,
};

// Enum GbxUISettings.ESubtitlesBackgroundOpacity
// NumValues: 0x0006
enum class ESubtitlesBackgroundOpacity : uint8
{
	Clear                                    = 0,
	Low                                      = 1,
	Medium                                   = 2,
	High                                     = 3,
	Solid                                    = 4,
	ESubtitlesBackgroundOpacity_MAX          = 5,
};

// ScriptStruct GbxUISettings.SubtitleFormat
// 0x0006 (0x0006 - 0x0000)
struct FSubtitleFormat final
{
public:
	uint8                                         Pad_0[0x6];                                        // 0x0000(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSubtitleFormat;

// ScriptStruct GbxUISettings.InputSettingsGamepadMapping
// 0x0020 (0x0020 - 0x0000)
struct FInputSettingsGamepadMapping final
{
public:
	class FName                                   Name;                                              // 0x0000(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FKey                                   Key;                                               // 0x0008(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FInputSettingsGamepadMapping;

}

