#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GbxUICoreGame

#include "Basic.hpp"

#include "GbxGame_structs.hpp"


namespace SDK
{

// ScriptStruct GbxUICoreGame.GbxUIDisplayDataDef
// 0x0000 (0x0018 - 0x0018)
struct FGbxUIDisplayDataDef : public FGbxUIDisplayDataBaseDef
{
};
DUMPER7_ASSERTS_FGbxUIDisplayDataDef;

// ScriptStruct GbxUICoreGame.GbxUIDisplayDataDef_LocalizedText
// 0x0010 (0x0028 - 0x0018)
struct FGbxUIDisplayDataDef_LocalizedText : public FGbxUIDisplayDataDef
{
public:
	class FText                                   Text;                                              // 0x0018(0x0010)(Edit, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGbxUIDisplayDataDef_LocalizedText;

// ScriptStruct GbxUICoreGame.GbxUIDisplayDataDef_HeaderBodyText
// 0x0010 (0x0038 - 0x0028)
struct FGbxUIDisplayDataDef_HeaderBodyText : public FGbxUIDisplayDataDef_LocalizedText
{
public:
	class FText                                   Header;                                            // 0x0028(0x0010)(Edit, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGbxUIDisplayDataDef_HeaderBodyText;

// ScriptStruct GbxUICoreGame.GbxUIDisplayDataDef_Image
// 0x0028 (0x0040 - 0x0018)
struct FGbxUIDisplayDataDef_Image final : public FGbxUIDisplayDataDef
{
public:
	TSoftObjectPtr<class UTexture2D>              Image;                                             // 0x0018(0x0028)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGbxUIDisplayDataDef_Image;

// ScriptStruct GbxUICoreGame.GbxUIDisplayDataDef_UIListMenuEntryText
// 0x0000 (0x0028 - 0x0028)
struct FGbxUIDisplayDataDef_UIListMenuEntryText final : public FGbxUIDisplayDataDef_LocalizedText
{
};
DUMPER7_ASSERTS_FGbxUIDisplayDataDef_UIListMenuEntryText;

}

