#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GbxWorldPainter

#include "Basic.hpp"


namespace SDK::Params
{

// Function GbxWorldPainter.GbxWorldPainterBoxComponent.GetEditOptionNames
// 0x0010 (0x0010 - 0x0000)
struct GbxWorldPainterBoxComponent_GetEditOptionNames final
{
public:
	TArray<class FName>                           OutNames;                                          // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GbxWorldPainterBoxComponent_GetEditOptionNames;

}

