#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PDA_Gore_Blood_Def

#include "Basic.hpp"

#include "PDA_Gore_Blood_Def_classes.hpp"
#include "PDA_Gore_Blood_Def_parameters.hpp"


namespace SDK
{

// Function PDA_Gore_Blood_Def.PDA_Gore_Blood_Def_C.GetActorType
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class AActor>               ActorClass                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// TSubclassOf<class AActor>               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class AActor> UPDA_Gore_Blood_Def_C::GetActorType(TSubclassOf<class AActor> ActorClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PDA_Gore_Blood_Def_C", "GetActorType");

	Params::PDA_Gore_Blood_Def_C_GetActorType Parms{};

	Parms.ActorClass = ActorClass;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

