#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_DamageableDoorMask

#include "Basic.hpp"

#include "Script_DamageableDoorMask_classes.hpp"
#include "Script_DamageableDoorMask_parameters.hpp"


namespace SDK
{

// Function Script_DamageableDoorMask.Script_DamageableDoorMask_C.ExecuteUbergraph_Script_DamageableDoorMask
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_DamageableDoorMask_C::ExecuteUbergraph_Script_DamageableDoorMask(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_DamageableDoorMask_C", "ExecuteUbergraph_Script_DamageableDoorMask");

	Params::Script_DamageableDoorMask_C_ExecuteUbergraph_Script_DamageableDoorMask Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_DamageableDoorMask.Script_DamageableDoorMask_C.OnBeginPlay
// (Event, Public, BlueprintEvent)

void UScript_DamageableDoorMask_C::OnBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_DamageableDoorMask_C", "OnBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

