#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_PropagandaSpeaker_Collectible

#include "Basic.hpp"

#include "Script_PropagandaSpeaker_Collectible_classes.hpp"
#include "Script_PropagandaSpeaker_Collectible_parameters.hpp"


namespace SDK
{

// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.0__OnStateDisabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Zero__OnStateDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "0__OnStateDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.25__OnStateDisabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Two5__OnStateDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "25__OnStateDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.25__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Two5__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "25__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.50__OnStateDisabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Five0__OnStateDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "50__OnStateDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.50__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Five0__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "50__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.75__OnStateDisabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Seven5__OnStateDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "75__OnStateDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.75__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Seven5__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "75__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.ActivateEncounter
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakSpawnEncounter*               Encounter                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::ActivateEncounter(class AOakSpawnEncounter* Encounter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "ActivateEncounter");

	Params::Script_PropagandaSpeaker_Collectible_C_ActivateEncounter Parms{};

	Parms.Encounter = Encounter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Active__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Active__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Active__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.AfterBuffer
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::AfterBuffer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "AfterBuffer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.CheckForPropaganda
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::CheckForPropaganda()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "CheckForPropaganda");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.CheckpointReached__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::CheckpointReached__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "CheckpointReached__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Complete__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Complete__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Complete__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.DebugPrint_NumPlayersInProximity
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::DebugPrint_NumPlayersInProximity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "DebugPrint_NumPlayersInProximity");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Echo4_Arrived
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakDrone*                        Echo4_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::Echo4_Arrived(class AOakDrone* Echo4_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Echo4_Arrived");

	Params::Script_PropagandaSpeaker_Collectible_C_Echo4_Arrived Parms{};

	Parms.Echo4_0 = Echo4_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Echo4_MoveTo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MoveTarget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::Echo4_MoveTo(class AActor* MoveTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Echo4_MoveTo");

	Params::Script_PropagandaSpeaker_Collectible_C_Echo4_MoveTo Parms{};

	Parms.MoveTarget = MoveTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Echo4_SetOrientationMode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    On_                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::Echo4_SetOrientationMode(bool On_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Echo4_SetOrientationMode");

	Params::Script_PropagandaSpeaker_Collectible_C_Echo4_SetOrientationMode Parms{};

	Parms.On_ = On_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Echo4_SkipRetrieve
// (Public, BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Echo4_SkipRetrieve()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Echo4_SkipRetrieve");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Echo4_Spawn
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EGbxRelativeLocationType                Relative_Location_Type                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Location_Option_Socket                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGbxRelativeRotation&      Location_Options_Offset_Direction                      (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  Location_Options_Offset_Distance                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::Echo4_Spawn(class AActor* Context, EGbxRelativeLocationType Relative_Location_Type, class FName Location_Option_Socket, const struct FGbxRelativeRotation& Location_Options_Offset_Direction, double Location_Options_Offset_Distance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Echo4_Spawn");

	Params::Script_PropagandaSpeaker_Collectible_C_Echo4_Spawn Parms{};

	Parms.Context = Context;
	Parms.Relative_Location_Type = Relative_Location_Type;
	Parms.Location_Option_Socket = Location_Option_Socket;
	Parms.Location_Options_Offset_Direction = std::move(Location_Options_Offset_Direction);
	Parms.Location_Options_Offset_Distance = Location_Options_Offset_Distance;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Echo_Spawned
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakDrone*                        Echo4_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::Echo_Spawned(class AOakDrone* Echo4_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Echo_Spawned");

	Params::Script_PropagandaSpeaker_Collectible_C_Echo_Spawned Parms{};

	Parms.Echo4_0 = Echo4_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.EncounterComplete__OnStateDisabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::EncounterComplete__OnStateDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "EncounterComplete__OnStateDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.EncounterComplete__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::EncounterComplete__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "EncounterComplete__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.ExecuteUbergraph_Script_PropagandaSpeaker_Collectible
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::ExecuteUbergraph_Script_PropagandaSpeaker_Collectible(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "ExecuteUbergraph_Script_PropagandaSpeaker_Collectible");

	Params::Script_PropagandaSpeaker_Collectible_C_ExecuteUbergraph_Script_PropagandaSpeaker_Collectible Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Fail__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Fail__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Fail__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.GbxActorScriptEvt__UsableActorState_K2_OnUsed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           User                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EUsabilityType                          UseType                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasHeld                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::GbxActorScriptEvt__UsableActorState_K2_OnUsed(class AActor* User, EUsabilityType UseType, bool bWasHeld)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "GbxActorScriptEvt__UsableActorState_K2_OnUsed");

	Params::Script_PropagandaSpeaker_Collectible_C_GbxActorScriptEvt__UsableActorState_K2_OnUsed Parms{};

	Parms.User = User;
	Parms.UseType = UseType;
	Parms.bWasHeld = bWasHeld;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.Idle__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::Idle__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "Idle__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnBeginPlay
// (Event, Public, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::OnBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnFinishedLoading
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsComplete                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::OnFinishedLoading(bool bIsComplete)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnFinishedLoading");

	Params::Script_PropagandaSpeaker_Collectible_C_OnFinishedLoading Parms{};

	Parms.bIsComplete = bIsComplete;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnPlayerEnter_AudioProximity
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void UScript_PropagandaSpeaker_Collectible_C::OnPlayerEnter_AudioProximity(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnPlayerEnter_AudioProximity");

	Params::Script_PropagandaSpeaker_Collectible_C_OnPlayerEnter_AudioProximity Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnPlayerEnter_Box
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::OnPlayerEnter_Box(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnPlayerEnter_Box");

	Params::Script_PropagandaSpeaker_Collectible_C_OnPlayerEnter_Box Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnPlayerEnter_Shared
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::OnPlayerEnter_Shared(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnPlayerEnter_Shared");

	Params::Script_PropagandaSpeaker_Collectible_C_OnPlayerEnter_Shared Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnPlayerEnter_Sphere
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void UScript_PropagandaSpeaker_Collectible_C::OnPlayerEnter_Sphere(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnPlayerEnter_Sphere");

	Params::Script_PropagandaSpeaker_Collectible_C_OnPlayerEnter_Sphere Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnPlayerLeave_AudioProximity
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::OnPlayerLeave_AudioProximity(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnPlayerLeave_AudioProximity");

	Params::Script_PropagandaSpeaker_Collectible_C_OnPlayerLeave_AudioProximity Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnPlayerLeave_Box
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::OnPlayerLeave_Box(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnPlayerLeave_Box");

	Params::Script_PropagandaSpeaker_Collectible_C_OnPlayerLeave_Box Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnPlayerLeave_Shared
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::OnPlayerLeave_Shared(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnPlayerLeave_Shared");

	Params::Script_PropagandaSpeaker_Collectible_C_OnPlayerLeave_Shared Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnPlayerLeave_Sphere
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::OnPlayerLeave_Sphere(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnPlayerLeave_Sphere");

	Params::Script_PropagandaSpeaker_Collectible_C_OnPlayerLeave_Sphere Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.OnTutorialRadiusEnter
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void UScript_PropagandaSpeaker_Collectible_C::OnTutorialRadiusEnter(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "OnTutorialRadiusEnter");

	Params::Script_PropagandaSpeaker_Collectible_C_OnTutorialRadiusEnter Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.PropagandaOn__OnStateDisabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::PropagandaOn__OnStateDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "PropagandaOn__OnStateDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.PropagandaOn__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::PropagandaOn__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "PropagandaOn__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.ReevaluateSpeaker
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::ReevaluateSpeaker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "ReevaluateSpeaker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.ReplaceHackingPlayer
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::ReplaceHackingPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "ReplaceHackingPlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.RetrieveE4
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DelayBeforeDigistructingOut                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::RetrieveE4(double DelayBeforeDigistructingOut)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "RetrieveE4");

	Params::Script_PropagandaSpeaker_Collectible_C_RetrieveE4 Parms{};

	Parms.DelayBeforeDigistructingOut = DelayBeforeDigistructingOut;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.SendSpeakerBackToIdle
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::SendSpeakerBackToIdle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "SendSpeakerBackToIdle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.SetProgressCheckpoint
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::SetProgressCheckpoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "SetProgressCheckpoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.SpawnAndSetEcho4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakCharacter*                    player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::SpawnAndSetEcho4(class AOakCharacter* player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "SpawnAndSetEcho4");

	Params::Script_PropagandaSpeaker_Collectible_C_SpawnAndSetEcho4 Parms{};

	Parms.player = player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.StartProgressTimer
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::StartProgressTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "StartProgressTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.SteamOn__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::SteamOn__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "SteamOn__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.UpdateHackProgress
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::UpdateHackProgress()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "UpdateHackProgress");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.UpdatePlayersInProximity
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGbxCharacter*                    player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Remove                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::UpdatePlayersInProximity(class AGbxCharacter* player, bool Remove)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "UpdatePlayersInProximity");

	Params::Script_PropagandaSpeaker_Collectible_C_UpdatePlayersInProximity Parms{};

	Parms.player = player;
	Parms.Remove = Remove;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.UpdatePlayersInProximity_Audio
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGbxCharacter*                    player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Remove                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::UpdatePlayersInProximity_Audio(class AGbxCharacter* player, bool Remove)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "UpdatePlayersInProximity_Audio");

	Params::Script_PropagandaSpeaker_Collectible_C_UpdatePlayersInProximity_Audio Parms{};

	Parms.player = player;
	Parms.Remove = Remove;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.UpdateProgressNumber
// (BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::UpdateProgressNumber()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "UpdateProgressNumber");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.UpdateSpeakerAudio
// (Public, BlueprintCallable, BlueprintEvent)

void UScript_PropagandaSpeaker_Collectible_C::UpdateSpeakerAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "UpdateSpeakerAudio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_PropagandaSpeaker_Collectible.Script_PropagandaSpeaker_Collectible_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_PropagandaSpeaker_Collectible_C::UserConstructionScript(class AActor* Actor) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_PropagandaSpeaker_Collectible_C", "UserConstructionScript");

	Params::Script_PropagandaSpeaker_Collectible_C_UserConstructionScript Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}

}

