#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_GlideVent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GbxAudio_structs.hpp"
#include "GbxGame_classes.hpp"


namespace SDK
{

// GbxActorScriptClass Script_GlideVent.Script_GlideVent_C
// 0x0038 (0x00D8 - 0x00A0)
class UScript_GlideVent_C final : public UGbxActorScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGbxAudioEvent                         OnUsed;                                            // 0x00A8(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_Script_GlideVent(int32 entrypoint);
	void GbxActorScriptEvt__OnActorBeginOverlap(class AActor* OverlappedActor, class AActor* OtherActor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Script_GlideVent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Script_GlideVent_C")
	}
	static class UScript_GlideVent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScript_GlideVent_C>();
	}
};
DUMPER7_ASSERTS_UScript_GlideVent_C;

}

