#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_SpawnMesh_Pad

#include "Basic.hpp"

#include "Enum_SpawnMesh_Pad_Size_structs.hpp"
#include "GbxGame_classes.hpp"
#include "Enum_SpawnMesh_Pad_Backing_structs.hpp"


namespace SDK
{

// GbxActorScriptClass Script_SpawnMesh_Pad.Script_SpawnMesh_Pad_C
// 0x0008 (0x00B0 - 0x00A8)
class UScript_SpawnMesh_Pad_C final : public UGbxActorScript_SpawnPoint
{
public:
	Enum_SpawnMesh_Pad_Size                       PadSize;                                           // 0x00A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_SpawnMesh_Pad_Backing                    PadBacking;                                        // 0x00A9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript(class AActor* Actor) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Script_SpawnMesh_Pad_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Script_SpawnMesh_Pad_C")
	}
	static class UScript_SpawnMesh_Pad_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScript_SpawnMesh_Pad_C>();
	}
};
DUMPER7_ASSERTS_UScript_SpawnMesh_Pad_C;

}

