#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_Carryable_ExplodingObject_PropaneTank

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GbxGame_classes.hpp"


namespace SDK
{

// GbxActorScriptClass Script_Carryable_ExplodingObject_PropaneTank.Script_Carryable_ExplodingObject_PropaneTank_C
// 0x0030 (0x00D0 - 0x00A0)
class UScript_Carryable_ExplodingObject_PropaneTank_C final : public UGbxActorScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AOakCharacter*                          instigator;                                        // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	FGameDataHandleProperty_                      Damage_Data;                                       // 0x00B0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AController*                            Details_Instigated_By;                             // 0x00C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Script_Carryable_ExplodingObject_PropaneTank(int32 entrypoint);
	void Exploding__OnStateEnabled();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Script_Carryable_ExplodingObject_PropaneTank_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Script_Carryable_ExplodingObject_PropaneTank_C")
	}
	static class UScript_Carryable_ExplodingObject_PropaneTank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScript_Carryable_ExplodingObject_PropaneTank_C>();
	}
};
DUMPER7_ASSERTS_UScript_Carryable_ExplodingObject_PropaneTank_C;

}

