#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_Lootable_Deco_Microwave

#include "Basic.hpp"

#include "Script_Lootable_Deco_Microwave_classes.hpp"
#include "Script_Lootable_Deco_Microwave_parameters.hpp"


namespace SDK
{

// Function Script_Lootable_Deco_Microwave.Script_Lootable_Deco_Microwave_C.ExecuteUbergraph_Script_Lootable_Deco_Microwave
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_Lootable_Deco_Microwave_C::ExecuteUbergraph_Script_Lootable_Deco_Microwave(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_Lootable_Deco_Microwave_C", "ExecuteUbergraph_Script_Lootable_Deco_Microwave");

	Params::Script_Lootable_Deco_Microwave_C_ExecuteUbergraph_Script_Lootable_Deco_Microwave Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_Lootable_Deco_Microwave.Script_Lootable_Deco_Microwave_C.Locked__OnStateDisabled
// (BlueprintCallable, BlueprintEvent)

void UScript_Lootable_Deco_Microwave_C::Locked__OnStateDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_Lootable_Deco_Microwave_C", "Locked__OnStateDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_Lootable_Deco_Microwave.Script_Lootable_Deco_Microwave_C.Locked__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_Lootable_Deco_Microwave_C::Locked__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_Lootable_Deco_Microwave_C", "Locked__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_Lootable_Deco_Microwave.Script_Lootable_Deco_Microwave_C.Open__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_Lootable_Deco_Microwave_C::Open__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_Lootable_Deco_Microwave_C", "Open__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}

}

