#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_BossFight_FrackingDrillSite

#include "Basic.hpp"

#include "Script_BossFight_FrackingDrillSite_classes.hpp"
#include "Script_BossFight_FrackingDrillSite_parameters.hpp"


namespace SDK
{

// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.CE_Boss2Died
// (BlueprintCallable, BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::CE_Boss2Died()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "CE_Boss2Died");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.CE_Boss2Spawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_FrackingDrillSite_C::CE_Boss2Spawned(class ASpawner* Spawner, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "CE_Boss2Spawned");

	Params::Script_BossFight_FrackingDrillSite_C_CE_Boss2Spawned Parms{};

	Parms.Spawner = Spawner;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.CE_Boss3Died
// (BlueprintCallable, BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::CE_Boss3Died()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "CE_Boss3Died");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.CE_Boss3Spawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_FrackingDrillSite_C::CE_Boss3Spawned(class ASpawner* Spawner, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "CE_Boss3Spawned");

	Params::Script_BossFight_FrackingDrillSite_C_CE_Boss3Spawned Parms{};

	Parms.Spawner = Spawner;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.CE_BossDied
// (BlueprintCallable, BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::CE_BossDied()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "CE_BossDied");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.CE_BossSpawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_FrackingDrillSite_C::CE_BossSpawned(class ASpawner* Spawner, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "CE_BossSpawned");

	Params::Script_BossFight_FrackingDrillSite_C_CE_BossSpawned Parms{};

	Parms.Spawner = Spawner;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.CE_OpenPreWaveSpawned_DoOnce
// (BlueprintCallable, BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::CE_OpenPreWaveSpawned_DoOnce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "CE_OpenPreWaveSpawned_DoOnce");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.CE_PreBossWaveSpawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_FrackingDrillSite_C::CE_PreBossWaveSpawned(class ASpawner* Spawner, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "CE_PreBossWaveSpawned");

	Params::Script_BossFight_FrackingDrillSite_C_CE_PreBossWaveSpawned Parms{};

	Parms.Spawner = Spawner;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.ExecuteUbergraph_Script_BossFight_FrackingDrillSite
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_FrackingDrillSite_C::ExecuteUbergraph_Script_BossFight_FrackingDrillSite(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "ExecuteUbergraph_Script_BossFight_FrackingDrillSite");

	Params::Script_BossFight_FrackingDrillSite_C_ExecuteUbergraph_Script_BossFight_FrackingDrillSite Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.GbxActorScriptEvt__OnBossArenaReset
// (BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::GbxActorScriptEvt__OnBossArenaReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "GbxActorScriptEvt__OnBossArenaReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.GbxActorScriptEvt__OnBossFightActive
// (BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::GbxActorScriptEvt__OnBossFightActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "GbxActorScriptEvt__OnBossFightActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.GbxActorScriptEvt__OnBossFightComplete
// (BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::GbxActorScriptEvt__OnBossFightComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "GbxActorScriptEvt__OnBossFightComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.GbxActorScriptEvt__OnBossFightPending
// (BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::GbxActorScriptEvt__OnBossFightPending()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "GbxActorScriptEvt__OnBossFightPending");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.OnBeginPlay
// (Event, Public, BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::OnBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "OnBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.SpawnAdds
// (Public, BlueprintCallable, BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::SpawnAdds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "SpawnAdds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_FrackingDrillSite.Script_BossFight_FrackingDrillSite_C.SpawnAddWave
// (BlueprintEvent)

void UScript_BossFight_FrackingDrillSite_C::SpawnAddWave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_FrackingDrillSite_C", "SpawnAddWave");

	UObject::ProcessEvent(Func, nullptr);
}

}

