#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Seq_MeteorDestroyer_Railgun_Lid

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Seq_MeteorDestroyer_Railgun_Lid.Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C
// 0x0008 (0x0050 - 0x0048)
class USeq_MeteorDestroyer_Railgun_Lid_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0048(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun__Event(class ACarryableObjectContainer* CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_);
	void ExecuteUbergraph_Seq_MeteorDestroyer_Railgun_Lid_DirectorBP(int32 entrypoint);
	void SequenceEvent__ENTRYPOINTSeq_MeteorDestroyer_Railgun_Lid_DirectorBP(class ACarryableObjectContainer* CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C")
	}
	static class USeq_MeteorDestroyer_Railgun_Lid_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USeq_MeteorDestroyer_Railgun_Lid_DirectorBP_C>();
	}
};
DUMPER7_ASSERTS_USeq_MeteorDestroyer_Railgun_Lid_DirectorBP_C;

}

