#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Seq_MeteorDestroyer_Railgun_Lid

#include "Basic.hpp"

#include "Seq_MeteorDestroyer_Railgun_Lid_classes.hpp"
#include "Seq_MeteorDestroyer_Railgun_Lid_parameters.hpp"


namespace SDK
{

// Function Seq_MeteorDestroyer_Railgun_Lid.Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C.CarryableObjectContainer_(BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun)_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACarryableObjectContainer*        CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USeq_MeteorDestroyer_Railgun_Lid_DirectorBP_C::CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun__Event(class ACarryableObjectContainer* CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C", "CarryableObjectContainer_(BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun)_Event");

	Params::Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C_CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun__Event Parms{};

	Parms.CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_ = CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Seq_MeteorDestroyer_Railgun_Lid.Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C.ExecuteUbergraph_Seq_MeteorDestroyer_Railgun_Lid_DirectorBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USeq_MeteorDestroyer_Railgun_Lid_DirectorBP_C::ExecuteUbergraph_Seq_MeteorDestroyer_Railgun_Lid_DirectorBP(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C", "ExecuteUbergraph_Seq_MeteorDestroyer_Railgun_Lid_DirectorBP");

	Params::Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C_ExecuteUbergraph_Seq_MeteorDestroyer_Railgun_Lid_DirectorBP Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Seq_MeteorDestroyer_Railgun_Lid.Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C.SequenceEvent__ENTRYPOINTSeq_MeteorDestroyer_Railgun_Lid_DirectorBP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACarryableObjectContainer*        CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USeq_MeteorDestroyer_Railgun_Lid_DirectorBP_C::SequenceEvent__ENTRYPOINTSeq_MeteorDestroyer_Railgun_Lid_DirectorBP(class ACarryableObjectContainer* CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C", "SequenceEvent__ENTRYPOINTSeq_MeteorDestroyer_Railgun_Lid_DirectorBP");

	Params::Seq_MeteorDestroyer_Railgun_Lid_DirectorBP_C_SequenceEvent__ENTRYPOINTSeq_MeteorDestroyer_Railgun_Lid_DirectorBP Parms{};

	Parms.CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_ = CarryableObjectContainer__BodyData_Body_Carryable_Container_Meteor_Destroyer_Railgun_;

	UObject::ProcessEvent(Func, &Parms);
}

}

