#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Seq_IO_Evocarium_Beacon

#include "Basic.hpp"

#include "Seq_IO_Evocarium_Beacon_classes.hpp"
#include "Seq_IO_Evocarium_Beacon_parameters.hpp"


namespace SDK
{

// Function Seq_IO_Evocarium_Beacon.Seq_IO_Evocarium_Beacon_DirectorBP_C.ExecuteUbergraph_Seq_IO_Evocarium_Beacon_DirectorBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USeq_IO_Evocarium_Beacon_DirectorBP_C::ExecuteUbergraph_Seq_IO_Evocarium_Beacon_DirectorBP(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_IO_Evocarium_Beacon_DirectorBP_C", "ExecuteUbergraph_Seq_IO_Evocarium_Beacon_DirectorBP");

	Params::Seq_IO_Evocarium_Beacon_DirectorBP_C_ExecuteUbergraph_Seq_IO_Evocarium_Beacon_DirectorBP Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Seq_IO_Evocarium_Beacon.Seq_IO_Evocarium_Beacon_DirectorBP_C.InteractiveSwitch_(GbxActorDef_IO_Switch_Evocarium_Beacon)_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AInteractiveSwitch*               InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USeq_IO_Evocarium_Beacon_DirectorBP_C::InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon__Event(class AInteractiveSwitch* InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_IO_Evocarium_Beacon_DirectorBP_C", "InteractiveSwitch_(GbxActorDef_IO_Switch_Evocarium_Beacon)_Event");

	Params::Seq_IO_Evocarium_Beacon_DirectorBP_C_InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon__Event Parms{};

	Parms.InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_ = InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Seq_IO_Evocarium_Beacon.Seq_IO_Evocarium_Beacon_DirectorBP_C.InteractiveSwitch_(GbxActorDef_IO_Switch_Evocarium_Beacon)_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AInteractiveSwitch*               InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USeq_IO_Evocarium_Beacon_DirectorBP_C::InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon__Event_0(class AInteractiveSwitch* InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_IO_Evocarium_Beacon_DirectorBP_C", "InteractiveSwitch_(GbxActorDef_IO_Switch_Evocarium_Beacon)_Event_0");

	Params::Seq_IO_Evocarium_Beacon_DirectorBP_C_InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon__Event_0 Parms{};

	Parms.InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_ = InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Seq_IO_Evocarium_Beacon.Seq_IO_Evocarium_Beacon_DirectorBP_C.SequenceEvent__ENTRYPOINTSeq_IO_Evocarium_Beacon_DirectorBP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AInteractiveSwitch*               InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USeq_IO_Evocarium_Beacon_DirectorBP_C::SequenceEvent__ENTRYPOINTSeq_IO_Evocarium_Beacon_DirectorBP(class AInteractiveSwitch* InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_IO_Evocarium_Beacon_DirectorBP_C", "SequenceEvent__ENTRYPOINTSeq_IO_Evocarium_Beacon_DirectorBP");

	Params::Seq_IO_Evocarium_Beacon_DirectorBP_C_SequenceEvent__ENTRYPOINTSeq_IO_Evocarium_Beacon_DirectorBP Parms{};

	Parms.InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_ = InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Seq_IO_Evocarium_Beacon.Seq_IO_Evocarium_Beacon_DirectorBP_C.SequenceEvent__ENTRYPOINTSeq_IO_Evocarium_Beacon_DirectorBP_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AInteractiveSwitch*               InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USeq_IO_Evocarium_Beacon_DirectorBP_C::SequenceEvent__ENTRYPOINTSeq_IO_Evocarium_Beacon_DirectorBP_0(class AInteractiveSwitch* InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_IO_Evocarium_Beacon_DirectorBP_C", "SequenceEvent__ENTRYPOINTSeq_IO_Evocarium_Beacon_DirectorBP_0");

	Params::Seq_IO_Evocarium_Beacon_DirectorBP_C_SequenceEvent__ENTRYPOINTSeq_IO_Evocarium_Beacon_DirectorBP_0 Parms{};

	Parms.InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_ = InteractiveSwitch__GbxActorDef_IO_Switch_Evocarium_Beacon_;

	UObject::ProcessEvent(Func, &Parms);
}

}

