#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Seq_MeteorDestroyer_Railgun_Receptacle

#include "Basic.hpp"

#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Seq_MeteorDestroyer_Railgun_Receptacle.Seq_MeteorDestroyer_Railgun_Receptacle_DirectorBP_C
// 0x0000 (0x0048 - 0x0048)
class USeq_MeteorDestroyer_Railgun_Receptacle_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Seq_MeteorDestroyer_Railgun_Receptacle_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Seq_MeteorDestroyer_Railgun_Receptacle_DirectorBP_C")
	}
	static class USeq_MeteorDestroyer_Railgun_Receptacle_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USeq_MeteorDestroyer_Railgun_Receptacle_DirectorBP_C>();
	}
};
DUMPER7_ASSERTS_USeq_MeteorDestroyer_Railgun_Receptacle_DirectorBP_C;

}

