#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Seq_SiloBase_Deployed_17000

#include "Basic.hpp"

#include "Seq_SiloBase_Deployed_17000_classes.hpp"
#include "Seq_SiloBase_Deployed_17000_parameters.hpp"


namespace SDK
{

// Function Seq_SiloBase_Deployed_17000.Seq_SiloBase_Deployed_17000_DirectorBP_C.ExecuteUbergraph_Seq_SiloBase_Deployed_17000_DirectorBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USeq_SiloBase_Deployed_17000_DirectorBP_C::ExecuteUbergraph_Seq_SiloBase_Deployed_17000_DirectorBP(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_SiloBase_Deployed_17000_DirectorBP_C", "ExecuteUbergraph_Seq_SiloBase_Deployed_17000_DirectorBP");

	Params::Seq_SiloBase_Deployed_17000_DirectorBP_C_ExecuteUbergraph_Seq_SiloBase_Deployed_17000_DirectorBP Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Seq_SiloBase_Deployed_17000.Seq_SiloBase_Deployed_17000_DirectorBP_C.SequenceEvent__ENTRYPOINTSeq_SiloBase_Deployed_17000_DirectorBP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASiloBaseObject*                  SiloBaseObject__GbxActorDef_IO_SiloBase_               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USeq_SiloBase_Deployed_17000_DirectorBP_C::SequenceEvent__ENTRYPOINTSeq_SiloBase_Deployed_17000_DirectorBP(class ASiloBaseObject* SiloBaseObject__GbxActorDef_IO_SiloBase_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_SiloBase_Deployed_17000_DirectorBP_C", "SequenceEvent__ENTRYPOINTSeq_SiloBase_Deployed_17000_DirectorBP");

	Params::Seq_SiloBase_Deployed_17000_DirectorBP_C_SequenceEvent__ENTRYPOINTSeq_SiloBase_Deployed_17000_DirectorBP Parms{};

	Parms.SiloBaseObject__GbxActorDef_IO_SiloBase_ = SiloBaseObject__GbxActorDef_IO_SiloBase_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Seq_SiloBase_Deployed_17000.Seq_SiloBase_Deployed_17000_DirectorBP_C.SiloBaseObject_(GbxActorDef_IO_SiloBase)_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASiloBaseObject*                  SiloBaseObject__GbxActorDef_IO_SiloBase_               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USeq_SiloBase_Deployed_17000_DirectorBP_C::SiloBaseObject__GbxActorDef_IO_SiloBase__Event(class ASiloBaseObject* SiloBaseObject__GbxActorDef_IO_SiloBase_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Seq_SiloBase_Deployed_17000_DirectorBP_C", "SiloBaseObject_(GbxActorDef_IO_SiloBase)_Event");

	Params::Seq_SiloBase_Deployed_17000_DirectorBP_C_SiloBaseObject__GbxActorDef_IO_SiloBase__Event Parms{};

	Parms.SiloBaseObject__GbxActorDef_IO_SiloBase_ = SiloBaseObject__GbxActorDef_IO_SiloBase_;

	UObject::ProcessEvent(Func, &Parms);
}

}

