#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatusEffect_Shock

#include "Basic.hpp"

#include "StatusEffect_Shock_classes.hpp"
#include "StatusEffect_Shock_parameters.hpp"


namespace SDK
{

// Function StatusEffect_Shock.StatusEffect_Shock_Script_Const_C.OnBegin
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FGbxStatusEffectScript_ExecContext&execContext                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UStatusEffect_Shock_Script_Const_C::OnBegin(const struct FGbxStatusEffectScript_ExecContext& execContext) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatusEffect_Shock_Script_Const_C", "OnBegin");

	Params::StatusEffect_Shock_Script_Const_C_OnBegin Parms{};

	Parms.execContext = std::move(execContext);

	UObject::ProcessEvent(Func, &Parms);
}

}

