#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatusEffect_Cryo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GbxEngine_structs.hpp"
#include "GbxGame_structs.hpp"
#include "GbxGame_classes.hpp"


namespace SDK
{

// GbxStatusEffectScriptClass StatusEffect_Cryo.StatusEffect_Cryo_Script_Instanced_C
// 0x0038 (0x0098 - 0x0060)
class UStatusEffect_Cryo_Script_Instanced_C final : public UGbxStatusEffectScript_Instanced
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0060(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FDataTableValueHandle                  CryoDoT_Handle;                                    // 0x0068(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	double                                        CryoDamageMultiplier;                              // 0x0090(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_StatusEffect_Cryo_Script_Instanced(int32 entrypoint);
	void K2Node_GbxStatusEffectPushEvent_0_Evt_MaxChargeReached(const class UObject* owner, const struct FGameplayTagContainer& tags, const struct FGbxStatusEffectSpec_Params& params);
	void OnBegin();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("StatusEffect_Cryo_Script_Instanced_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StatusEffect_Cryo_Script_Instanced_C")
	}
	static class UStatusEffect_Cryo_Script_Instanced_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStatusEffect_Cryo_Script_Instanced_C>();
	}
};
DUMPER7_ASSERTS_UStatusEffect_Cryo_Script_Instanced_C;

}

