#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_Enhancement_Modifiers

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Struct_Enhancement_Modifiers.Struct_Enhancement_Modifiers
// 0x0020 (0x0020 - 0x0000)
struct FStruct_Enhancement_Modifiers final
{
public:
	double                                        Modifier_7_A313317241BC2D878A73D2927050A307;       // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Duration_13_ED0E585D4C428C2FB29833BA7E9A956B;      // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Comment_15_BDC8799F407964EC1418E082E68CA3BB;       // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FStruct_Enhancement_Modifiers;

}

