#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: T_NPC_Echo4_Hello_02

#include "Basic.hpp"

#include "T_NPC_Echo4_Hello_02_classes.hpp"
#include "T_NPC_Echo4_Hello_02_parameters.hpp"


namespace SDK
{

// Function T_NPC_Echo4_Hello_02.T_NPC_Echo4_Hello_02_Script_Instanced_C.ExecuteUbergraph_T_NPC_Echo4_Hello_02_Script_Instanced
// (Final, UbergraphFunction)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UT_NPC_Echo4_Hello_02_Script_Instanced_C::ExecuteUbergraph_T_NPC_Echo4_Hello_02_Script_Instanced(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("T_NPC_Echo4_Hello_02_Script_Instanced_C", "ExecuteUbergraph_T_NPC_Echo4_Hello_02_Script_Instanced");

	Params::T_NPC_Echo4_Hello_02_Script_Instanced_C_ExecuteUbergraph_T_NPC_Echo4_Hello_02_Script_Instanced Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function T_NPC_Echo4_Hello_02.T_NPC_Echo4_Hello_02_Script_Instanced_C.OnBegin_Mut
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UT_NPC_Echo4_Hello_02_Script_Instanced_C::OnBegin_Mut(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("T_NPC_Echo4_Hello_02_Script_Instanced_C", "OnBegin_Mut");

	Params::T_NPC_Echo4_Hello_02_Script_Instanced_C_OnBegin_Mut Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function T_NPC_Echo4_Hello_02.T_NPC_Echo4_Hello_02_Script_Instanced_C.OnEnd_Mut
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EGbxTrickEnd                            EndType                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UT_NPC_Echo4_Hello_02_Script_Instanced_C::OnEnd_Mut(class AActor* Actor, EGbxTrickEnd EndType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("T_NPC_Echo4_Hello_02_Script_Instanced_C", "OnEnd_Mut");

	Params::T_NPC_Echo4_Hello_02_Script_Instanced_C_OnEnd_Mut Parms{};

	Parms.Actor = Actor;
	Parms.EndType = EndType;

	UObject::ProcessEvent(Func, &Parms);
}

}

