#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TLoop_SpawnMesh_Drill_Small

#include "Basic.hpp"

#include "TLoop_SpawnMesh_Drill_Small_classes.hpp"
#include "TLoop_SpawnMesh_Drill_Small_parameters.hpp"


namespace SDK
{

// Function TLoop_SpawnMesh_Drill_Small.TLoop_SpawnMesh_Drill_Small_Script_Instanced_C.ExecuteUbergraph_TLoop_SpawnMesh_Drill_Small_Script_Instanced
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTLoop_SpawnMesh_Drill_Small_Script_Instanced_C::ExecuteUbergraph_TLoop_SpawnMesh_Drill_Small_Script_Instanced(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TLoop_SpawnMesh_Drill_Small_Script_Instanced_C", "ExecuteUbergraph_TLoop_SpawnMesh_Drill_Small_Script_Instanced");

	Params::TLoop_SpawnMesh_Drill_Small_Script_Instanced_C_ExecuteUbergraph_TLoop_SpawnMesh_Drill_Small_Script_Instanced Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TLoop_SpawnMesh_Drill_Small.TLoop_SpawnMesh_Drill_Small_Script_Instanced_C.GbxTrickNotifyEvt_TrickNotify._EnemySpecific_Notify
// (BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UTLoop_SpawnMesh_Drill_Small_Script_Instanced_C::GbxTrickNotifyEvt_TrickNotify__EnemySpecific_Notify(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TLoop_SpawnMesh_Drill_Small_Script_Instanced_C", "GbxTrickNotifyEvt_TrickNotify._EnemySpecific_Notify");

	Params::TLoop_SpawnMesh_Drill_Small_Script_Instanced_C_GbxTrickNotifyEvt_TrickNotify__EnemySpecific_Notify Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TLoop_SpawnMesh_Drill_Small.TLoop_SpawnMesh_Drill_Small_Script_Instanced_C.GbxTrickNotifyEvt_TrickNotify.Melee.AOE_Notify
// (BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UTLoop_SpawnMesh_Drill_Small_Script_Instanced_C::GbxTrickNotifyEvt_TrickNotify_Melee_AOE_Notify(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TLoop_SpawnMesh_Drill_Small_Script_Instanced_C", "GbxTrickNotifyEvt_TrickNotify.Melee.AOE_Notify");

	Params::TLoop_SpawnMesh_Drill_Small_Script_Instanced_C_GbxTrickNotifyEvt_TrickNotify_Melee_AOE_Notify Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TLoop_SpawnMesh_Drill_Small.TLoop_SpawnMesh_Drill_Small_Script_Instanced_C.OnBegin_Mut
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UTLoop_SpawnMesh_Drill_Small_Script_Instanced_C::OnBegin_Mut(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TLoop_SpawnMesh_Drill_Small_Script_Instanced_C", "OnBegin_Mut");

	Params::TLoop_SpawnMesh_Drill_Small_Script_Instanced_C_OnBegin_Mut Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TLoop_SpawnMesh_Drill_Small.TLoop_SpawnMesh_Drill_Small_Script_Instanced_C.OnEnd_Mut
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EGbxTrickEnd                            EndType                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTLoop_SpawnMesh_Drill_Small_Script_Instanced_C::OnEnd_Mut(class AActor* Actor, EGbxTrickEnd EndType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TLoop_SpawnMesh_Drill_Small_Script_Instanced_C", "OnEnd_Mut");

	Params::TLoop_SpawnMesh_Drill_Small_Script_Instanced_C_OnEnd_Mut Parms{};

	Parms.Actor = Actor;
	Parms.EndType = EndType;

	UObject::ProcessEvent(Func, &Parms);
}

}

