#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TLoop_SpawnMesh_Drill_Small

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GbxGame_structs.hpp"
#include "GbxGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TLoop_SpawnMesh_Drill_Small.TLoop_SpawnMesh_Drill_Small_Script_Instanced_C
// 0x0008 (0x0048 - 0x0040)
class UTLoop_SpawnMesh_Drill_Small_Script_Instanced_C final : public UGbxTrickScript_Loop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0040(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_TLoop_SpawnMesh_Drill_Small_Script_Instanced(int32 entrypoint);
	void GbxTrickNotifyEvt_TrickNotify__EnemySpecific_Notify(class AActor* Actor);
	void GbxTrickNotifyEvt_TrickNotify_Melee_AOE_Notify(class AActor* Actor);
	void OnBegin_Mut(class AActor* Actor);
	void OnEnd_Mut(class AActor* Actor, EGbxTrickEnd EndType);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TLoop_SpawnMesh_Drill_Small_Script_Instanced_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TLoop_SpawnMesh_Drill_Small_Script_Instanced_C")
	}
	static class UTLoop_SpawnMesh_Drill_Small_Script_Instanced_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTLoop_SpawnMesh_Drill_Small_Script_Instanced_C>();
	}
};
DUMPER7_ASSERTS_UTLoop_SpawnMesh_Drill_Small_Script_Instanced_C;

}

