#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TrickScriptLoop_SpawnMesh_Dropship

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GbxGame_structs.hpp"
#include "GbxGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TrickScriptLoop_SpawnMesh_Dropship.TrickScriptLoop_SpawnMesh_Dropship_C
// 0x0008 (0x0048 - 0x0040)
class UTrickScriptLoop_SpawnMesh_Dropship_C final : public UGbxTrickScript_Loop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0040(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_TrickScriptLoop_SpawnMesh_Dropship(int32 entrypoint);
	void OnBegin_Mut(class AActor* Actor);
	void OnEnd_Mut(class AActor* Actor, EGbxTrickEnd EndType);
	void OnLoop_Mut(class AActor* Actor, int32 LoopCount);
	void OnLoopEnd_Mut(class AActor* Actor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TrickScriptLoop_SpawnMesh_Dropship_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TrickScriptLoop_SpawnMesh_Dropship_C")
	}
	static class UTrickScriptLoop_SpawnMesh_Dropship_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTrickScriptLoop_SpawnMesh_Dropship_C>();
	}
};
DUMPER7_ASSERTS_UTrickScriptLoop_SpawnMesh_Dropship_C;

}

