#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TravelStationLabel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OakGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TravelStationLabel.WBP_TravelStationLabel_C
// 0x0008 (0x02E0 - 0x02D8)
class UWBP_TravelStationLabel_C final : public UOakUILabelWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Construct();
	void ExecuteUbergraph_WBP_TravelStationLabel(int32 entrypoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TravelStationLabel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TravelStationLabel_C")
	}
	static class UWBP_TravelStationLabel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TravelStationLabel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TravelStationLabel_C;

}

